repos:
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
        args:
          - --extra-keys
          - metadata.kernelspec
          - metadata.language_info
          - metadata.anaconda-cloud
