name: Test Jupyter Notebooks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-notebooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest nbval pydna

      - name: Run Jupyter Notebook Tests
        run: |
          shopt -s globstar
          cd notebooks
          export PYTHONWARNINGS="ignore:Feature qualifier key 'ApEinfo_graphicformat' is longer than maximum length specified by standard"
          pytest -vvv --import-mode=importlib --current-env --capture=no --nbval **/*.ipynb
